language: cpp
before_install: sudo apt update && sudo apt install -y libssl-dev
jobs:
  include:
    - stage: test
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test2
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test3
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test4
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test5
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test6
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test7
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - stage: test8
      script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
    - script: make && ./vanitygen -r '^15w95pznz362FvFHMfmLn1AYrLQcjKnHUB$'
